version: '3'

services:
  nats-server:
    image: nats:latest
    ports:
      - "8222:8222"


  client-gateway:
    build: ./client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:3001
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3001
      - NATS_SERVERS=${NATS_URL}:${NATS_PORT}

#Auth MS
  auth-ms:
    depends_on:
      - homes-db
    build: ./auth-ms
    volumes:
      - ./auth-ms/src:/usr/src/app/src
    command: sh -c "npm run typeorm migration:run && npm run start:dev"
    environment:
      - PORT=${AUTH_PORT}
      - NATS_SERVERS=${NATS_URL}:${NATS_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${AUTH_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOME_HOST}
      - JWT_SECRET=${JWT_SECRET}
      - TYPEORM_CONNECTION=${TYPEORM_CONNECTION}
      - TYPEORM_HOST=${POSTGRES_HOME_HOST}
      - TYPEORM_USERNAME=${POSTGRES_USER}
      - TYPEORM_PASSWORD=${POSTGRES_PASSWORD}
      - TYPEORM_DATABASE=${AUTH_DB}
      - TYPEORM_PORT=${POSTGRES_PORT}
      - NODE_ENV=${NODE_ENV}

#Home MS
  home-ms:
    depends_on:
      - homes-db
    build: ./home-ms
    volumes:
      - ./home-ms/src:/usr/src/app/src
    command: sh -c "npm run typeorm migration:run && npm run start:dev"
    environment:
      - PORT=${HOME_PORT}
      - NATS_SERVERS=${NATS_URL}:${NATS_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${HOME_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOME_HOST}
      - JWT_SECRET=${JWT_SECRET}
      - TYPEORM_CONNECTION=${TYPEORM_CONNECTION}
      - TYPEORM_HOST=${POSTGRES_HOME_HOST}
      - TYPEORM_USERNAME=${POSTGRES_USER}
      - TYPEORM_PASSWORD=${POSTGRES_PASSWORD}
      - TYPEORM_DATABASE=${HOME_DB}
      - TYPEORM_PORT=${POSTGRES_PORT}
      - NODE_ENV=${NODE_ENV}

  homes-db:
    container_name: home-database
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=23Ron16*
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
